/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 DonaldsBoat.glb -T 
Files: DonaldsBoat.glb [602.68KB] > F:\My Documents\Sites games\ice-slide\public\models\DonaldsBoat-transformed.glb [74.25KB] (88%)
Author: ToontownModels (https://sketchfab.com/ToontownModels)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/donalds-boat-e1021848b7534b19a72b6803bed3ca6b
Title: donalds_boat
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useStore } from "@/hooks/useStore";

export function ModelDonaldsBoat(props) {
    const darkMode = useStore((state) => state.darkMode);

    const { nodes, materials } = useGLTF(
        "models/DonaldsBoat-transformed.glb",
    );
    // Helper to darken material if darkMode
    function getMaterial(mat) {
        if (!darkMode) return mat;
        // Clone material to avoid mutating shared instance
        const darkMat = mat.clone();
        if (darkMat.color) {
            darkMat.color.multiplyScalar(0.1);
        }
        if (darkMat.emissive) {
            darkMat.emissive.multiplyScalar(1);
        }
        return darkMat;
    }

    return (
        <group
            {...props}
            dispose={null}
            // scale={100}
        >
            <mesh
                geometry={nodes.above_water_Shader14_0.geometry}
                material={getMaterial(materials.Shader14)}
                scale={0.01}
            />
            <mesh
                geometry={nodes.above_water_Shader15_0.geometry}
                material={getMaterial(materials.Shader15)}
                scale={0.01}
            />
            {/* Slight tweak from 0.01 to avoid zindex flash */}
            <mesh
                geometry={nodes.above_water_Shader11_0.geometry}
                material={getMaterial(materials.Shader11)}
                scale={0.00992}
            />
            <mesh
                geometry={nodes.decals_Shader16_0.geometry}
                material={getMaterial(materials.Shader16)}
                scale={0.01}
            />
            <mesh
                geometry={nodes.decals_Shader_0.geometry}
                material={getMaterial(materials.Shader)}
                scale={0.01}
            />
            <mesh
                geometry={nodes.decals_Shader3_0.geometry}
                material={getMaterial(materials.Shader3)}
                scale={0.01}
            />
            <mesh
                geometry={nodes.below_water_Shader10_0.geometry}
                material={getMaterial(materials.Shader10)}
                scale={0.01}
            />
            <mesh
                geometry={nodes.o3_lambert9_0.geometry}
                material={getMaterial(materials.lambert9)}
                scale={0.01}
            />
            <mesh
                geometry={nodes.ground_Shader2_0.geometry}
                material={getMaterial(materials.Shader2)}
                scale={0.01}
            />
            <mesh
                geometry={nodes.wheel_house_walls_exterior_Shader6_0.geometry}
                material={getMaterial(materials.Shader6)}
                scale={0.01}
            />
            <mesh
                geometry={nodes.wheel_house_walls_exterior_Shader7_0.geometry}
                material={getMaterial(materials.Shader7)}
                scale={0.01}
            />
            <mesh
                geometry={nodes.wheel_house_walls_exterior_Shader8_0.geometry}
                material={getMaterial(materials.Shader8)}
                scale={0.01}
            />
            <mesh
                geometry={nodes.wheel_house_walls_exterior_Shader9_0.geometry}
                material={getMaterial(materials.Shader9)}
                scale={0.01}
            />
            <mesh
                geometry={nodes.wheel_house_roof_Shader12_0.geometry}
                material={getMaterial(materials.Shader12)}
                scale={0.01}
            />
            <mesh
                geometry={nodes.wheel_house_steam_pipe_Shader13_0.geometry}
                material={getMaterial(materials.Shader13)}
                scale={0.01}
            />
            <mesh
                geometry={nodes.boat_whistle_Shader5_0.geometry}
                material={getMaterial(materials.Shader5)}
                scale={0.01}
            />
            <mesh
                geometry={nodes.wheel_Shader4_0.geometry}
                material={getMaterial(materials.Shader4)}
                scale={0.01}
            />
            <mesh
                geometry={nodes.wheel_house_front_wall_Shader1_0.geometry}
                material={getMaterial(materials.Shader1)}
                scale={0.01}
            />
            <mesh
                geometry={nodes.window_frame_Shader17_0.geometry}
                material={getMaterial(materials.Shader17)}
                scale={0.01}
            />
        </group>
    );
}

useGLTF.preload("models/toontown/DonaldsBoat-transformed.glb");
