/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

// const link = `${process.env.NEXT_PUBLIC_CDN}games/Race Game/witch.gltf`
const link = `models/flunky.glb`

export default function CogFlunky(props) {
    const { nodes, materials } = useGLTF(link)
    return (
        <group {...props} dispose={null}>
            <group>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh004.geometry}
                    material={materials.cog_shoe}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh004_1.geometry}
                    material={materials.sellbot_leg}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh004_2.geometry}
                    material={materials.sellbot_sleeve}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh004_3.geometry}
                    material={materials.sellbot_blazer}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh004_4.geometry}
                    material={materials.cog_neck}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh004_5.geometry}
                    material={materials.cog_hand}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh004_6.geometry}
                    material={materials.cog_arm}
                />
            </group>
            <group>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh033.geometry}
                    material={materials.cog_head_flunky}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh033_1.geometry}
                    material={materials.cog_flunky_glasses}
                />
            </group>
        </group>
    )
}

useGLTF.preload(link)