/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Jumprope.glb -T 
Files: Jumprope.glb [213.59KB] > F:\My Documents\Sites games\tug-of-war\public\models\Jumprope-transformed.glb [17.27KB] (92%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelJumprope(props) {
  const { nodes, materials } = useGLTF('models/Jumprope-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Line003_1.geometry} material={materials['13___Default']} />
      <mesh geometry={nodes.Line003_1_1.geometry} material={materials['14___Default']} />
      <mesh geometry={nodes.Line003_1_2.geometry} material={materials['15___Default']} />
    </group>
  )
}

useGLTF.preload('models/Jumprope-transformed.glb')
