/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 MostRecent.glb -T --keepnames 
Files: MostRecent.glb [40.18MB] > F:\My Documents\Sites games\cannon\public\models\MostRecent-transformed.glb [32.39MB] (19%)
*/

import React, { useEffect, useState, useMemo } from "react";
import * as THREE from "three";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export default function ModelMostRecentToon({
    action,
    actionIndex,
    isWalking,
    isJumping,
    jumpTrigger,
    isSprinting,
    isSwimming,
    isFishing,
    isGrounded,
    ...props
}) {
    const group = React.useRef();
    const prevActionRef = React.useRef();

    const { scene, animations } = useGLTF(
        "models/MostRecent-transformed.glb",
    );
    const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
    const { nodes, materials } = useGraph(clone);

    const trimmedAnimations = useMemo(() => {
        return animations.map((clip) => {
            const fps = 30;
            const startFrame = 1;

            return THREE.AnimationUtils.subclip(
                clip,
                clip.name,
                startFrame,
                Math.floor(clip.duration * fps),
                fps,
            );
        });
    }, [animations]);

    // Extract the mixer so we can listen to animation events
    const { actions, mixer } = useAnimations(trimmedAnimations, group);

    // Track if a jump is currently playing
    const [isJumpLocked, setIsJumpLocked] = useState(false);

    const ANIMATION_FRAME_RATE = 30;
    const FRAME_OFFSET = 1 / ANIMATION_FRAME_RATE;

    const skipFirstFrame = (action) => {
        if (!action) return;

        action.reset();

        // move off frame 0 immediately
        action.time = FRAME_OFFSET;

        // force mixer evaluation
        action.getMixer()?.update(0.0001);
    };

    useEffect(() => {
        if (!mixer || !actions) return;

        const handleLoop = (e) => {
            const action = e.action;

            if (!action) return;

            // jump clips don't loop
            if (action.getLoop() === THREE.LoopOnce) return;

            action.time = FRAME_OFFSET;
        };

        mixer.addEventListener("loop", handleLoop);

        return () => {
            mixer.removeEventListener("loop", handleLoop);
        };
    }, [mixer, actions]);

    // 1. Lock the state when a jump event is triggered
    useEffect(() => {
        if (jumpTrigger > 0) {
            setIsJumpLocked(true);
        }
    }, [jumpTrigger]);

    // 2. Unlock the state when the jump animation finishes
    useEffect(() => {
        if (!mixer) return;

        const handleFinished = (e) => {
            // Check if the action that just finished is the jump clip
            if (e.action.getClip().name === "medium_shorts_toon_rig|leap_z") {
                setIsJumpLocked(false);
            }
        };

        mixer.addEventListener("finished", handleFinished);
        return () => mixer.removeEventListener("finished", handleFinished);
    }, [mixer]);

    // Resolve a zero-based animation index, falling back to the named action.
    const selectedAction =
        (Number.isInteger(actionIndex)
            ? trimmedAnimations[actionIndex]?.name
            : undefined) || action;

    // 3. JUMP LOCKED OVERRIDES ALL: Checked first in the chain
    const effectiveAction = isFishing
        ? "medium_shorts_toon_rig|fish"
        : isSwimming
          ? "medium_shorts_toon_rig|swim"
          : isJumpLocked
            ? // 'medium_shorts_toon_rig|jump'
              "medium_shorts_toon_rig|leap_z"
            : isSprinting
              ? "medium_shorts_toon_rig|run"
              : isWalking
                ? "medium_shorts_toon_rig|walk"
                : selectedAction || "medium_shorts_toon_rig|neutral";

    // THE FIX: Mimic Blender's Alpha Clip/Dithered mode
    useMemo(() => {
        if (materials.atlas2) {
            materials.atlas2.transparent = false; // Disable standard WebGL blending
            materials.atlas2.depthWrite = true; // Force writing to the depth buffer
            materials.atlas2.alphaTest = 0.5; // Discard pixels below 50% opacity (adjust if edges look too thick/thin)
        }
    }, [materials]);

    useEffect(() => {
        if (!actions) return;

        const nextAction = actions[effectiveAction] || null;
        const prevAction = prevActionRef.current || null;

        // Helper function to configure actions based on their type
        const configureAction = (act, actionName) => {
            if (actionName === "medium_shorts_toon_rig|leap_z") {
                const clipDuration = act.getClip().duration;
                // Scale playback speed so it finishes in exactly 1 second
                act.setEffectiveTimeScale(clipDuration);
                act.setLoop(THREE.LoopOnce, 1);
                act.clampWhenFinished = true; // Essential so it doesn't snap back before fading out
            } else {
                // Reset timescale and loop behavior for walks/runs/idles
                act.setEffectiveTimeScale(1);
                act.setLoop(THREE.LoopRepeat, Infinity);
                act.clampWhenFinished = false;
            }
            act.enabled = true;
        };

        // If the action hasn't changed, ensure it's playing and return
        if (nextAction) {
            skipFirstFrame(nextAction);
            configureAction(nextAction, effectiveAction);
            nextAction.play();
        }

        // Fade out previous action
        if (prevAction && nextAction) {
            prevAction.crossFadeTo(nextAction, 0.2, true);
        }

        // Fade in new action
        if (nextAction) {
            skipFirstFrame(nextAction);
            configureAction(nextAction, effectiveAction);

            nextAction.fadeIn(0.2).play();
        }

        prevActionRef.current = nextAction;

        return () => {
            if (nextAction && typeof nextAction.fadeOut === "function") {
                nextAction.fadeOut(0.2);
            }
        };
    }, [effectiveAction, actions]);

    return (
        <group
            ref={group}
            {...props}
            dispose={null}
            scale={[-0.011, 0.011, 0.011]}
        >
            <group name="Scene">
                <group name="Armature">
                    <primitive object={nodes._rootJoint} />
                </group>
                <skinnedMesh
                    name="Arms"
                    geometry={nodes.Arms.geometry}
                    material={materials.atlas2}
                    skeleton={nodes.Arms.skeleton}
                />
                <skinnedMesh
                    name="Clothing"
                    geometry={nodes.Clothing.geometry}
                    material={materials.atlas2}
                    skeleton={nodes.Clothing.skeleton}
                />
                <skinnedMesh
                    name="Dog_Face_Features"
                    geometry={nodes.Dog_Face_Features.geometry}
                    material={materials.atlas2}
                    skeleton={nodes.Dog_Face_Features.skeleton}
                />
                <skinnedMesh
                    name="Eyeballs"
                    geometry={nodes.Eyeballs.geometry}
                    material={materials.atlas2}
                    skeleton={nodes.Eyeballs.skeleton}
                />
                <skinnedMesh
                    name="Eyes"
                    geometry={nodes.Eyes.geometry}
                    material={materials.atlas2}
                    skeleton={nodes.Eyes.skeleton}
                />
                <skinnedMesh
                    name="Hands"
                    geometry={nodes.Hands.geometry}
                    material={materials.atlas2}
                    skeleton={nodes.Hands.skeleton}
                />
                <skinnedMesh
                    name="Head"
                    geometry={nodes.Head.geometry}
                    material={materials.atlas2}
                    skeleton={nodes.Head.skeleton}
                />
                <skinnedMesh
                    name="Legs"
                    geometry={nodes.Legs.geometry}
                    material={materials.atlas2}
                    skeleton={nodes.Legs.skeleton}
                />
                <skinnedMesh
                    name="Sleeves"
                    geometry={nodes.Sleeves.geometry}
                    material={materials.atlas2}
                    skeleton={nodes.Sleeves.skeleton}
                />
            </group>
        </group>
    );
}

useGLTF.preload("models/toontown/MostRecent-transformed.glb");
