/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ..\Models\GLB format\rocks-tall.glb --output output\rocks-tall.js --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
const link = `${process.env.NEXT_PUBLIC_CDN}games/Assets/KennyNL/Graveyard/Models/rocks-tall.glb`;

export function ModelKennyNLGraveyardRocksTall(props) {
  const { nodes, materials } = useGLTF(link)
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes['rocks-tall_1'].geometry} material={materials.colormap} />
    </group>
  )
}

useGLTF.preload(link)
