/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 models\Shark.glb --output output\Shark.js --transform --keepnames --shadows 
Files: models\Shark.glb [124.87KB] > F:\My Documents\Articles Media\AMCOT\Models\Quaternius\Fishing\JSX\output\Shark-transformed.glb [32.81KB] (74%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

const link = `${process.env.NEXT_PUBLIC_CDN}games/Assets/Quaternius/Fishing/Shark.glb`

export function ModelQuaterniusFishingShark(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF(link)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Fish_Armature">
          <primitive object={nodes.Main1} />
        </group>
        <group name="Shark">
          <skinnedMesh name="Icosphere010" geometry={nodes.Icosphere010.geometry} material={materials.Shark_Dark} skeleton={nodes.Icosphere010.skeleton} />
          <skinnedMesh name="Icosphere010_1" geometry={nodes.Icosphere010_1.geometry} material={materials.Shark_Main} skeleton={nodes.Icosphere010_1.skeleton} />
          <skinnedMesh name="Icosphere010_2" geometry={nodes.Icosphere010_2.geometry} material={materials.Shark_Light} skeleton={nodes.Icosphere010_2.skeleton} />
          <skinnedMesh name="Icosphere010_3" geometry={nodes.Icosphere010_3.geometry} material={materials.Eyes} skeleton={nodes.Icosphere010_3.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(link)
