/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 models\ship_wreck.gltf --output output\ship_wreck.js --transform --keepnames --shadows 
Files: models\ship_wreck.gltf [6.79KB] > F:\My Documents\Articles Media\AMCOT\Models\Kenny\kenney_pirate-kit\JSX\output\ship_wreck-transformed.glb [13.46KB] (-98%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
const link = `${process.env.NEXT_PUBLIC_CDN}games/Assets/KennyNL/Pirate/Models/ship_wreck.glb`;

export function ModelKennyNLPirateShipWreck(props) {
  const { nodes, materials } = useGLTF(link)
  return (
    <group {...props} dispose={null}>
      <group name="ship_wreck_8angles" position={[9.255, 0, 0.014]}>
        <mesh name="ship_wreck_8angles_1" castShadow receiveShadow geometry={nodes.ship_wreck_8angles_1.geometry} material={materials.PaletteMaterial002} />
        <mesh name="ship_wreck_8angles_2" castShadow receiveShadow geometry={nodes.ship_wreck_8angles_2.geometry} material={materials.PaletteMaterial001} />
      </group>
    </group>
  )
}

useGLTF.preload(link)
