/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 models\Soldier.gltf --output output\Soldier.js --transform 
Files: models\Soldier.gltf [3.35MB] > E:\Downloads\women\output\Soldier-transformed.glb [770.16KB] (77%)
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

const link = `${process.env.NEXT_PUBLIC_CDN}games/Assets/Quaternius/women/Soldier-transformed.glb`

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF(link)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  useEffect(() => {

    console.log("Actions", actions)

    actions[`Idle`].play();

}, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
        </group>
        <group name="Soldier_Body">
          <skinnedMesh name="Cube057" geometry={nodes.Cube057.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube057.skeleton} />
          <skinnedMesh name="Cube057_1" geometry={nodes.Cube057_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube057_1.skeleton} />
          <skinnedMesh name="Cube057_2" geometry={nodes.Cube057_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube057_2.skeleton} />
        </group>
        <group name="Soldier_Feet">
          <skinnedMesh name="Cube000" geometry={nodes.Cube000.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube000.skeleton} />
          <skinnedMesh name="Cube000_1" geometry={nodes.Cube000_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube000_1.skeleton} />
        </group>
        <group name="Soldier_Head">
          <skinnedMesh name="Cube036" geometry={nodes.Cube036.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube036.skeleton} />
          <skinnedMesh name="Cube036_1" geometry={nodes.Cube036_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube036_1.skeleton} />
          <skinnedMesh name="Cube036_2" geometry={nodes.Cube036_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube036_2.skeleton} />
        </group>
        <group name="Soldier_Legs">
          <skinnedMesh name="Cube041" geometry={nodes.Cube041.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube041.skeleton} />
          <skinnedMesh name="Cube041_1" geometry={nodes.Cube041_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube041_1.skeleton} />
          <skinnedMesh name="Cube041_2" geometry={nodes.Cube041_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube041_2.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(link)
