/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: anderlenolan (https://sketchfab.com/anderlenolan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toontown-dog-b801481012814c4db29f7ad084efd62c
Title: Toontown Dog
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

let link = '/models/toontown_dog.glb';

export default function ModelToon(props) {
  const { nodes, materials } = useGLTF(link)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.423}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group scale={0.25}>
            <primitive object={nodes._rootJoint} />
            <skinnedMesh
              geometry={nodes.Object_198.geometry}
              material={materials.atlas5}
              skeleton={nodes.Object_198.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_200.geometry}
              material={materials.atlas5}
              skeleton={nodes.Object_200.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_202.geometry}
              material={materials.atlas5}
              skeleton={nodes.Object_202.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(link)